### ISSUE TITLE
All in One 安装3.6版本时显示缺少 'yunion-fetcherfs' 包

### ISSUE THREAD

**Issue by iwtctww** [yunionio/onecloud#10333]
TASK [common : Install yunion common packages] *********************************
fatal: [    ]: FAILED! => {"changed": false, "msg": "No package matching 'yunion-fetcherfs' found available, installed or updated", "rc": 126, "results": ["All packages providing epel-release are up to date", "All packages providing libaio are up to date", "All packages providing lvm2 are up to date", "No package matching 'yunion-fetcherfs' found available, installed or updated"]}

**Comment by zexi** [comment]
3.6 的 yum 源是有这个包的，https://iso.yunion.io/3.6/rpms/packages/backup
重新试了下安装 3.6 也没有复现这个问题，安装的 config.yml 里面有没有指定 onecloud_version 为 v3.6.x ?

**Comment by iwtctww** [comment]
我是在ARM64的机器上安装的，应该是架构问题吧。周末用X64的机器重试没有问题。

**Comment by iwtctww** [comment]
> 3.6 的 yum 源是有这个包的，https://iso.yunion.io/3.6/rpms/packages/backup
> 重新试了下安装 3.6 也没有复现这个问题，安装的 config.yml 里面有没有指定 onecloud_version 为 v3.6.x ?

我是在ARM64的机器上安装的，应该是架构问题吧。周末用X64的机器重试没有问题。

**Comment by zexi** [comment]
ARM 的部署还没有支持，目前这个 PR： https://github.com/yunionio/ocboot/pull/39 正在对接 UOS arm 的支持，我们还在测试中。
另外问下你的 ARM 机器上运行的是 CentOS 吗？目前我们的计划对接 ARM 的发行版是 UOS 和 debian 。
