### ISSUE TITLE
资源同步，数据一致性问题

### ISSUE THREAD

**Issue by xuyue86** [yunionio/onecloud#10445]
咨询下一下场景是如何解决的
创建虚拟机，controller-》model-》task-》cloudprovider-》createVM
在createVM的指令下发后，上层的虚拟机状态是deploying,此时上层onecloud的pod挂掉了，重建pod后，这条脏数据应该如何处理。
或者说onecloud本身不保证操作时的数据强一致性，只保证最终的数据一致性，通过较长的时间来做全量数据的同步。
其他操作也是同理，虚拟机关机，关闭指令下发后，上层服务挂了，重启后，虚拟机状态还是关机中，此时无法做其他操作，只能等待下个周期的全量状态同步吗？

**Comment by ioito** [comment]
1. 在资源创建过程中，如果pod是在createVM之前挂掉的话，重建pod后上层的虚拟机是条脏数据，需要较长的时间全量同步才能保持数据的一致性，但可以仅同步一个区域的数据，加速数据一致
2. 如果是在createVM后并执行了db.SetExternalId后，上层的虚拟机就不算是脏数据，因为可以在pod重建后，仅需要同步下虚拟机的状态就可以保证数据一致
3. 虚拟机关机和 2 情况类型，仅需要同步下虚拟机状态就可以保证数据一致
总结: 
若资源本身已经保存了云上的Id(本地数据库中的external_id)，可以对单个资源进行同步操作就保证数据一致性
若资源的未保存云上id(本地数据库中的external_id为空),需要较长时间的数据同步才可以保证数据一致性

**Comment by xuyue86** [comment]
感谢回复，基本了解机制。
额外的问题：
除了云账号定期同步数据，上文中提及的同步操作按我理解应该是运维人员在主动发现状态不一致的问题后进行的手工同步是吧？

**Comment by ioito** [comment]
> 感谢回复，基本了解机制。
> 额外的问题：
> 除了云账号定期同步数据，上文中提及的同步操作按我理解应该是运维人员在主动发现状态不一致的问题后进行的手工同步是吧？

是的
