### ISSUE TITLE
sas3ircu工具在抓取磁盘数据时，字段Rotate一直为False，导致storage_type 为ssd

### ISSUE THREAD

**Issue by wangliang33** [yunionio/onecloud#10597]
**What happened**:
strings.HasSuffix 判断顺序反了
![image](https://user-images.githubusercontent.com/81805454/113405137-e3913f80-93db-11eb-9bb1-b7ae3d06412f.png)
导致字段Rotate一直为False，最终导致storage_type 为ssd
**What you expected to happen**:
字段Rotate在正确的时候为true
**How to reproduce it**:
一直打印222
![image](https://user-images.githubusercontent.com/81805454/113405316-3834ba80-93dc-11eb-9843-d5eaa3ea0ad4.png)
**Anything else we need to know?**:
无

**Comment by swordqiu** [comment]
@wangliang33 谢谢反馈，是否方便提一个PR？

**Comment by zexi** [comment]
> @wangliang33 谢谢反馈，是否方便提一个PR？

@wangliang33 感谢反馈，我这边已经提了个 PR fix ，sas2 raid 我们之前一直没有机器，所以测试不充分。后续还有问题麻烦及时反馈给我们。
