### ISSUE TITLE
Web UI support

### ISSUE THREAD

**Issue by zexi** [yunionio/onecloud#2401]
**What would you like to be added**:

需要能够管理云平台资源的 web UI 交互管理界面， 能够方便用户使用。

/cc @houjiazong

**Comment by zexi** [comment]
需要完成的基础功能如下：

# 主机页面

主机界面对应虚拟机相关资源的操作，需要前端开发以下功能

- [ ] 虚拟机相关操作
  - [ ] 创建，删除，开关机等生命周期操作
  - [ ] vnc, ssh 链接
  - [ ] 重装系统，重置密码
- [ ] 镜像相关操作
  - [ ] 上传，删除镜像
- [ ] 存储相关，硬盘列表
- [ ] 网络部分
  - [ ] 二层网络，vpc 子网，安全组， EIP
- [ ] 基础资源相关
  - [ ] 宿主机列表
  - [ ] 透传设备 GPU 列表
- [ ] 回收站支持

# 多云管理界面

多云管理界面提供云账号，私有云可用区管理

- [ ] 私有云区域(region)、可用区(zone) 列表
- [ ] 多云账号支持

# 系统配置界面

系统配置界面提供认证源，项目，用户管理的功能

- [ ] 用户管理支持
  - [ ] 认证源支持 LDAP， AD 对接
  - [ ] 支持用户、项目、角色的管理

**Comment by swordqiu** [comment]
9.20目标
[] 虚拟机相关操作
 [x] 列表
 [x] 创建，删除，开关机等生命周期操作
 [x] vnc, ssh 链接
 [] 重装系统，重置密码
[]镜像相关操作
 [x] 列表
 [] 上传，删除镜像
[] 存储相关
 [] 硬盘列表
[] 网络部分
 [] vpc
 [] 二层网络
 [] IP子网
 [] 安全组
 [] EIP
[] 基础资源相关
 [x] 宿主机列表
 [] 透传设备 GPU 列表
[] 回收站支持
 [x] 主机
 [] 磁盘
 [] 镜像
