### ISSUE TITLE
将 server create 的参数信息持久化

### ISSUE THREAD

**Issue by Zexi** [yunionio/onecloud#30]
**What would you like to be added**:

调用 server-create 接口时，将创建参数持久化到数据库。

**Why is this needed**:

实现克隆或者创建主备机等操作时，需要基于原机器的创建参数生成 api 调用参数。
主机现有的资源并不能重新生成创建时的参数。

**Comment by Zexi** [comment]
可以把 server-create 的参数存在 metadata 表里面，需要使用的时候直接从该表取出创建参数。

**Comment by wanyaoqi** [comment]
如果有deploy file的时候保存需要注意，metadata_tbl value的是TEXT的数据类型，最大64KB，可以考虑不保存deploy file

**Comment by Zexi** [comment]
> 如果有deploy file的时候保存需要注意，metadata_tbl value的是TEXT的数据类型，最大64KB，可以考虑不保存deploy file

这个确实是一个问题，应该不需要保存 deploy 的信息。
@wanyaoqi 我看 #74 已经实现了 clone 的功能，但不是使用的保存 metadata 的这种方式，到时候需要重新实现下？

**Comment by wanyaoqi** [comment]
> > 如果有deploy file的时候保存需要注意，metadata_tbl value的是TEXT的数据类型，最大64KB，可以考虑不保存deploy file
> 
> 这个确实是一个问题，应该不需要保存 deploy 的信息。
> @wanyaoqi 我看 #74 已经实现了 clone 的功能，但不是使用的保存 metadata 的这种方式，到时候需要重新实现下？

@Zexi 嗯，忘了，到时候实现的时候一并加了
- [ ] VM Clone使用metadata中保存的创建参数
