### ISSUE TITLE
host 和 host-deployer pod 启动失败

### ISSUE THREAD

**Issue by bolemon** [yunionio/onecloud#5274]
容器报错如下
host
[I 200227 15:42:55 hostinfo.NewHostInfo(hostinfo.go:1470)] CPU Model Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz Microcode 0x500002c
[E 200227 15:42:55 procutils.(*Command).Output(procutils.go:87)] Execute command "modprobe tun" , error: exit status 1 , output: modprobe: can't change directory to '/lib/modules': No such file or directory

[F 200227 15:42:55 hostman.(*SHostService).RunService(host_services.go:92)] Failed to activate tun/tap device

host-deployer
[E 200227 15:42:22 procutils.(*Command).Output(procutils.go:87)] Execute command "rmmod nbd" , error: exit status 1 , output: .rmmod.bin: ERROR: Module nbd is not currently loaded

[E 200227 15:42:22 deployserver.(*SDeployService).PrepareEnv(deployserver.go:249)] rmmod error: .rmmod.bin: ERROR: Module nbd is not currently loaded

[E 200227 15:42:22 procutils.(*Command).Output(procutils.go:87)] Execute command "modprobe nbd max_part=16" , error: exit status 1 , output: 
[F 200227 15:42:22 deployserver.(*SDeployService).InitService(deployserver.go:293)] Failed to activate nbd device: 

这个是什么原因呢

**Comment by zexi** [comment]
@bolemon 这个原因应该是宿主机上没有加载 nbd 模块
麻烦在宿主机上使用以下命令，看下宿主机的内核是否有 nbd 模块？

```bash
uname -a
modprobe nbd
```

**Comment by wanyaoqi** [comment]
@bolemon 应该是host版本和onecloud-operator版本不一致导致的
可以升级host和host-deployer版本来解决
``` sh
# 修改host的image,使用最新的 registry.cn-beijing.aliyuncs.com/yunionio/host:latest
kubectl edit daemonset -n onecloud default-host
# 修改host-deployer的image registry.cn-beijing.aliyuncs.com/yunionio/host-deployer:latest
kubectl edit daemonset -n onecloud default-host-deployer
# 然后删除host 和host-deployer的pod
kubectl delete pod -n onecloud default-host-xxx default-host-deployer-xxx
```
