### ISSUE TITLE
安装过程中总是运行到这里就出错？请问是什么原因

### ISSUE THREAD

**Issue by ctornado** [yunionio/onecloud#6484]
TASK [primary-master-node : Create onecloud web login user admin] **************************************************************************************************************************************************************************************************************
fatal: [10.1.131.154]: FAILED! => {"changed": true, "cmd": "eval $(/opt/yunion/bin/ocadm cluster rcadmin)\n/opt/yunion/bin/climc user-create --password admin@123 --enabled admin\n", "delta": "0:00:00.239029", "end": "2020-05-20 14:39:50.990319", "msg": "non-zero return code", "rc": 1, "start": "2020-05-20 14:39:50.751290", "stderr": "{\"error\":{\"class\":\"UnauthorizedError\",\"code\":401,\"data\":{\"fields\":[\"authUserByIdentityV3: Query user by name: Error 1146: Table 'keystone.user' doesn't exist\"],\"id\":\"unauthorized {0}\"},\"details\":\"unauthorized authUserByIdentityV3: Query user by name: Error 1146: Table 'keystone.user' doesn't exist\"}}", "stderr_lines": ["{\"error\":{\"class\":\"UnauthorizedError\",\"code\":401,\"data\":{\"fields\":[\"authUserByIdentityV3: Query user by name: Error 1146: Table 'keystone.user' doesn't exist\"],\"id\":\"unauthorized {0}\"},\"details\":\"unauthorized authUserByIdentityV3: Query user by name: Error 1146: Table 'keystone.user' doesn't exist\"}}"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************
10.1.131.154               : ok=51   changed=10   unreachable=0    failed=1    skipped=6    rescued=0    ignored=0

[root@iZ2zeifg1bwa257gpka727Z ocboot]#

**Comment by zexi** [comment]
@ctornado 请问是安装的哪个版本？

**Comment by ctornado** [comment]
> @ctornado 请问是安装的哪个版本？

最新版吧。我用的是你们在线文档的all-in-one安装方式，用的阿里云主机

**Comment by ctornado** [comment]
> @ctornado 请问是安装的哪个版本？

最新版吧。我用的是你们在线文档的all-in-one安装方式，用的阿里云主机
用ocboot安装的。

阿里云主机操作系统版本centos 7.7 64位

**Comment by ctornado** [comment]
@zexi 有没有简单易行的安装方式，感觉安装失败率有点高

**Comment by zexi** [comment]
> @zexi 有没有简单易行的安装方式，感觉安装失败率有点高

这个是代码的 bug，刚提了 PR 修复，可以用以下的方式回滚使用旧的版本部署:

```bash
# 登录到你的 aliyun 主机，回退到　v3.1.5-20200514.1　版本
$ ocadm cluster update --version v3.1.5-20200514.1 --wait

# 回到本机的 ocboot 目录再重复执行一遍 ./run config-xxx.yml
$ ./run config-xxx.yml 
```
这样应该可以部署好，麻烦试下

**Comment by ctornado** [comment]
@zexi 可以了，多谢。

**Comment by ctornado** [comment]
@zexi 另外问一下，你们系统里怎么不能新建项目呀？

**Comment by zexi** [comment]
> @zexi 另外问一下，你们系统里怎么不能新建项目呀？

目前开源的前端还没有做这部分，可以在后端用我们的命令行工具创建：
```bash
# source 认证信息
$ source <(ocadm cluster rcadmin)

# 创建项目
$ climc project-create --enabled project-test

# 查看创建好的项目
$ climc project-list 

# 创建用户
$ climc user-create --password pass@word --enabled test-user

# 查看角色
$ climc role-list
+----------------------------------+---------------+-----------+------------------------------------+-----------+
|                ID                |     Name      | Domain_Id |            Description             | is_public |
+----------------------------------+---------------+-----------+------------------------------------+-----------+
| 0dfd4940e60d4e6585e9d5a6fbf24016 | sa            | default   | 运维管理员                         | true      |
| 4ebb199153c64751888b9d82f8d843c9 | project_owner | default   | 项目主管                           | true      |
| 257d543668e7426c8740314e4d542059 | member        | default   | 普通成员                           | true      |
| c64f804edee64e4582c2f0fa8deb754b | fa            | default   | 财务管理员                         | true      |
| d056808d154e40648b7fd3d433b24015 | domainadmin   | default   | 域管理员                           | true      |
| 1e236948ed7f42f78aee5f4869edcd87 | admin         | default   | Boostrap system default admin role | false     |
+----------------------------------+---------------+-----------+------------------------------------+-----------+

# 将用户 test-user 以 member 角色加入项目 project-test
$ climc project-add-user project-test test-user member

# 然后就可以用 test-user 登录前端了
```
