### ISSUE TITLE
源码编译组件报错，是服务器缺少什么库文件吗？

### ISSUE THREAD

**Issue by Jorcyzz** [yunionio/onecloud#6647]
[root@i-yvriesdx onecloud-master]# make cmd/host-image/
fatal: Not a git repository (or any parent up to mount point /data)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /data)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /data)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
go build -mod vendor -ldflags "-w -X yunion.io/x/pkg/util/version.gitVersion= -X yunion.io/x/pkg/util/version.gitCommit= -X yunion.io/x/pkg/util/version.gitBranch= -X yunion.io/x/pkg/util/version.buildDate=2020-05-28T13:10:42Z -X yunion.io/x/pkg/util/version.gitTreeState=clean -X yunion.io/x/pkg/util/version.gitMajor=0 -X yunion.io/x/pkg/util/version.gitMinor=0" -o /data/go/src/onecloud-demo/onecloud-master/_output/bin/host-image yunion.io/x/onecloud/cmd/host-image/
# yunion.io/x/onecloud/pkg/hostimage
pkg/hostimage/image.go:20:23: fatal error: libqemuio.h: No such file or directory
 #include "libqemuio.h"
                       ^
compilation terminated.
make: *** [cmd/host-image/] 错误 2

**Comment by wanyaoqi** [comment]
@Jorcyzz 
这个组件编译依赖qemu的代码
默认可以不用编译这个 ，可以直接使用我们做好的rpm包 https://iso.yunion.cn/yumrepo-3.0/rpms/packages/host/host-image-1.0.5-1.el7.centos.x86_64.rpm
或者做好的docker镜像 registry.cn-beijing.aliyuncs.com/yunionio/host-base:latest，位置在 /opt/yunion/bin/host-image
