### ISSUE TITLE
climc 支持通过环境变量禁用 wrap line

### ISSUE THREAD

**Issue by zexi** [yunionio/onecloud#6710]
**What would you like to be added**:

climc 命令行工具显示 list 结果的时候可以关闭 line wrap

**Why is this needed**:

如果终端太窄， climc 打印 table 默认会 wrap，不方便复制，可以通过在外部设置环境变量的方式禁用这种显示。

![2020-06-03-143314_grim](https://user-images.githubusercontent.com/10767027/83603618-53118500-a5a7-11ea-9382-84839136af78.png)

/area climc

**Comment by wanyaoqi** [comment]
https://github.com/yunionio/pkg/pull/64

**Comment by zexi** [comment]
Already implement by https://github.com/yunionio/onecloud/pull/6752
/close
