### ISSUE TITLE
阿里云账单同步问题

### ISSUE THREAD

**Issue by iiiusky** [yunionio/onecloud#6759]
其他信息
健康状态
no permission

阿里云的账号信息中健康状态一直为
no permission

我给阿里云上的子账号按照你们的步骤给予了

AliyunRAMFullAccess
AliyunECSFullAccess 
AliyunCloudMonitorFullAccess 
这三种权限，怕不够，我还给予了全局oss 的可读权限
相对应的账号的桶也给予了该子账号的oss 只读权限。。为什么还是同步不到账单信息？

AliyunRAMFullAccess | 非必须权限，当子账号没有AccessKey时，需要此权限开创建新的AccessKey。
-- | --
AliyunECSFullAccess | 管理虚拟机服务(ECS)的权限，如果您需要管理虚拟机，请开启该权限。
AliyunCloudMonitorFullAccess | 管理云监控(CloudMonitor)的权限，此权限为必须权限

**Comment by ioito** [comment]
@iiiusky 文档没有写全，还需要 AliyunBSSReadOnlyAccess 权限(账单)
文档近期会更新
