### ISSUE TITLE
提交工单后会进行邮件通知吗？

### ISSUE THREAD

**Issue by iiiusky** [yunionio/onecloud#6762]
提交工单后会进行邮件通知吗？
或者可以设置个钉钉提醒啥的

**Comment by taishen** [comment]
配置了邮件服务器信息后，提交工单会有邮件通知。目前对接了邮件和短信，工单的钉钉通知正在做。

建议添加 OneCloud 壹云小助手 YunionIO 加入 OneCloud技术交流群。

**Comment by zhaoxiangchun** [comment]
工单的审批人会收到相应的审批邮件信息

**Comment by rainzm** [comment]
邮件服务器信息的配置方式可以查阅文档：https://docs.yunion.cn/docs/user/systemconfig/system/mailconfig/

**Comment by rainzm** [comment]
> 配置了邮件服务器信息后，提交工单会有邮件通知。目前对接了邮件和短信，工单的钉钉通知正在做。
> 
> 建议添加 OneCloud 壹云小助手 微信 “YunionIO” ，加入 OneCloud技术交流群。

邮件配置方式请参阅文档：
https://docs.yunion.cn/docs/user/systemconfig/system/mailconfig/

配置好后，您还需要为用户配置邮箱。

**Comment by iiiusky** [comment]
好像没有通知渠道，只有邮件短信。。

**Comment by rainzm** [comment]
> 好像没有通知渠道，只有邮件短信。。

是这样的，3.2版本之前只支持邮件短信，您也可以照常配置。

**Comment by rainzm** [comment]
> 好像没有通知渠道，只有邮件短信。。

是这样的，3.2 版本之前只支持邮件和短信，您可以照常配置邮件服务器信息。
3.2 版本开始，增加了钉钉（包含webhook机器人）以及飞书（包含webhook机器人）支持，并将菜单名由 '邮件短信' 改为 '通知渠道'。
关于版本信息，在web界面，可以点击右上角 '?' 中的 '关于' 查看。
