### ISSUE TITLE
有没有从源代码部署的文档

### ISSUE THREAD

**Issue by zhengheh** [yunionio/onecloud#6901]

**Comment by zexi** [comment]
有基于源码开发的文档：https://docs.yunion.io/docs/contribute/contrib/
这个文档里面包含如何从源码编译，和部署到集群里面调试的内容。
集群的创建可以基于快速开始文档：https://docs.yunion.io/docs/quickstart/；
如果想 step by step 搭建部署集群，可以参考文档：https://docs.yunion.io/docs/setup/controlplane/

**Comment by zhengheh** [comment]
非常感谢您的回复，着些文档都看过了，可以成功部署。 
只是部署过程好像是 ocadm 和 oncloud-operator 封装了。 部署过程还不够直白。 不太容易理解 数据库表是怎么建立的，初始化数据是怎么生成，服务启动的先后顺序是什么样的， 服务的注册和发现的过程是什么样的， 这些都对理解代码有帮助。 有类似的相关信息么

**Comment by zexi** [comment]
> 非常感谢您的回复，着些文档都看过了，可以成功部署。
> 只是部署过程好像是 ocadm 和 oncloud-operator 封装了。 部署过程还不够直白。 不太容易理解 数据库表是怎么建立的，初始化数据是怎么生成，服务启动的先后顺序是什么样的， 服务的注册和发现的过程是什么样的， 这些都对理解代码有帮助。 有类似的相关信息么

这部分的文档确实还没有写，我们需要添加下。
目前如果想了解可能需要看下各个组件代码，每个组件负责的功能大概是这样的：

- ocadm: 主要是在 Centos 上部署 k8s 集群的作用
  - 负责在 Centos 上部署 k8s 集群, 同时保存数据库连接信息
  - 部署完 k8s 集群后，会将 onecloud-operator 以 deployment 的方式部署到集群中
  - ocadm 会创建一个叫做 default 的 OnecloudCluster 资源

- onecloud-operator: 主要是在 k8s 集群之上部署 onecloud 各个服务组件，具体细节可以看[oneloud-operator 介绍文档](https://github.com/yunionio/onecloud-operator/blob/master/docs/intro.md)
  - 往 k8s 集群中注入 OnecloudCluster 这种 CRD 资源
  - 当 ocadm 创建一个 default 的 OnecloudCluster 时，就会安装部署 onecloud 相关的各个组件
    - 为每个服务创建数据库，配置用户密码
    - 创建(更新)各个服务的 k8s 资源(deployment, configmap 等等)
    - 为各个服务注册 endpoint，初始化其它配置等等

各个数据库的创建是由 onecloud-operator 负责的，但数据库的表初始化则是由服务自己决定的。我们的 https://github.com/yunionio/sqlchemy 库能根据 ORM 自动创建表。

服务的注册发现过程文档的 [后端服务框架介绍](https://docs.yunion.io/docs/contribute/framework/#%E8%AE%A4%E8%AF%81%E9%83%A8%E5%88%86)有简单的说明。另外每个服务的 endpoint 是由 onecloud-operator 自动注入的。

**Comment by zhengheh** [comment]
谢谢您的快速回复，我在看看您提供的这些资料，后续有问题在向您请教

**Comment by zexi** [comment]
> 谢谢您的快速回复，我在看看您提供的这些资料，后续有问题在向您请教

不客气，有问题直接提就好，我们会尽快回复
