### ISSUE TITLE
default-meter 服务对应的源代码在哪里？

### ISSUE THREAD

**Issue by zhengheh** [yunionio/onecloud#6902]
在 这个项目里么

![image](https://user-images.githubusercontent.com/6240748/85255364-b69b1e00-b494-11ea-9b90-a0a3c9e0524b.png)

**Comment by zexi** [comment]
目前 meter 的代码是不开源的，这个地方估计是 onecloud-operator 里面忘记禁用了，我们改进下。这个组件是计费用的，在商业版本里面会用到，onecloud-operator 可以支持部署开源版本和商业版本。

开源和商业版本的来回切换可以参考文档: https://docs.yunion.io/docs/setup/controlplane/#%E5%88%87%E6%8D%A2%E4%BC%81%E4%B8%9A%E7%89%88%E5%89%8D%E7%AB%AF

**Comment by zhengheh** [comment]
哦，原来这样。除了这个服务，上面列出的目前onecloud-operator 默认部署的服务，还有哪些是不开源的么。

另外，这个服务是”新建资源“的时候用到的，如果没有这个服务，哪开源版本还支持“新建资源“ 么， 怎么可以部署一个完全开源的系统呢？

**Comment by zexi** [comment]
> 哦，原来这样。除了这个服务，上面列出的目前onecloud-operator 默认部署的服务，还有哪些是不开源的么。

除了 meter 其它服务的源码应该都能在 onecloud 仓库里面找到

> 另外，这个服务是”新建资源“的时候用到的，如果没有这个服务，哪开源版本还支持“新建资源“ 么， 怎么可以部署一个完全开源的系统呢？

这个我们看下，开源的前端不应该调用 meter 这个服务的 api。没有这个服务，开源的版本也能创建资源，我们的目标就是如果部署开源的版本，肯定就是完全开源和稳定可用的，开源和商业的版本功能有清晰的界限。

这个 default-meter 的服务不应该出现在开源部署的环境中，这算个 bug，我们会修复下。

**Comment by zhengheh** [comment]
好的，非常感谢您的回复，期待这bug早日解决,  到时最好能有一个可以从git代码库部署开发环境的简单说明，区别于现在通过自动话脚本从镜像部署生产环境的文档。这样可以帮助感兴趣的开发者快速上手
