### ISSUE TITLE
latest onecloud-service-operator docker image is not found in the registry

### ISSUE THREAD

**Issue by lshmouse** [yunionio/onecloud#6974]
**What happened**:
onecloud-cluster-onecloud-service-operator started failed when starting latest version onecloud cluster on k8s using onecloud-operator.
There is no latest onecloud-service-operator docker image in the registry
```
Failed to pull image "registry.cn-beijing.aliyuncs.com/yunionio/onecloud-service-operator:latest": rpc error: code = Unknown desc = Error response from daemon: manifest for registry.cn-beijing.aliyuncs.com/yunionio/onecloud-service-operator:latest not found: manifest unknown: manifest unknown
```
**What you expected to happen**:
onecloud-service-operator on k8s starts successully.

**How to reproduce it**:
starting latest version onecloud cluster on k8s.
```
$ kubectl create -f onecloud-cluster.yaml
```
**Anything else we need to know?**:
Please help to upload the latest  onecloud-service-operator docker image. ThX~

**Environment**:
- OS (e.g: `cat /etc/os-release`):
  NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel (e.g. `uname -a`):
 Linux mi-OptiPlex-7070 5.3.0-59-generic #53~18.04.1-Ubuntu SMP Thu Jun 4 14:58:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by rainzm** [comment]
@lshmouse 
Thx for your issue. I have uploaded the docker image mentioned above.
However, the latest version is an unstable version. So please use the docker image with the specified version number, such as v3.2, in the normal env. And [onecloud-service-operator](https://github.com/yunionio/onecloud-service-operator) is in beta for now.

**Comment by lshmouse** [comment]
@rainzm OK. Thanks very much~
 I will specified the onecloud-operator and onecloud-cluster version to v3.1.5-20200525.0
