### ISSUE TITLE
The city/plateform/region/AZ of alicloud can't be listed when trying to create a vm on alicloud

### ISSUE THREAD

**Issue by lshmouse** [yunionio/onecloud#6980]
**What happened**:
I imported a alicloud account and created a vpc on it sucessfully. But when i try to create a vm on alicloud, there is no city/plateform/region/AZ listed on the UI.
![3](https://user-images.githubusercontent.com/118687/86141848-1c3a7a80-bb25-11ea-9c4a-c0a3e128cd7d.png)

![1](https://user-images.githubusercontent.com/118687/86141145-4b042100-bb24-11ea-8840-2afe1802c7a0.png)

The cloud regions can be listed using the climc tools.
![2](https://user-images.githubusercontent.com/118687/86141357-8acb0880-bb24-11ea-8e7c-744a38bef1cf.png)

**What you expected to happen**:
city/plateform/region/AZ can be listed on the UI and i can create a vm on alicloud

**How to reproduce it**:
- deploying onecloud-operator with version v3.1.5-20200525.0 on minikube
- deploying onecloud-cluster  with version v3.1.5-20200525.0 on minikube
- Import a  alicloud public cloud account and created a vpc
- Try to create a vm on alicloud

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
 ```
Linux mi-OptiPlex-7070 5.3.0-59-generic #53~18.04.1-Ubuntu SMP Thu Jun 4 14:58:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Others:

**Comment by zexi** [comment]
@swordqiu @houjiazong 感觉前端的创建过滤逻辑需要优化？

**Comment by lshmouse** [comment]
VPC can't be listed when create ip subnet.

![6](https://user-images.githubusercontent.com/118687/86145533-9bca4880-bb29-11ea-8d52-45f84f91f473.png)
![5](https://user-images.githubusercontent.com/118687/86145545-9ec53900-bb29-11ea-90a8-29184ebe8ca4.png)

**Comment by lshmouse** [comment]
![Screenshot from 2020-06-30 23-32-28](https://user-images.githubusercontent.com/118687/86145837-07141a80-bb2a-11ea-96c6-ecca981cac1d.png)

**Comment by lshmouse** [comment]
本质原因是阿里云账号的预付费的，我没有充值，导致相关sub net资源无法创建。
通过给阿里云账号充值，已经解决上述问题～ 多谢各位的支持～
