### ISSUE TITLE
文档：部署集群页面“控制节点作为计算节点”章节需补充添加climc创建宿主机IP子网内容；

### ISSUE THREAD

**Issue by dong0320** [yunionio/onecloud#8908]
**What happened**:
文档：部署集群页面“控制节点作为计算节点”章节需补充添加climc创建宿主机IP子网内容；
![image](https://user-images.githubusercontent.com/43448298/99933157-2ccde480-2d95-11eb-9e16-9df7fbfd00ea.png)
![image](https://user-images.githubusercontent.com/43448298/99933165-35261f80-2d95-11eb-9cee-3bdb99af1853.png)

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by zexi** [comment]
/close 
https://github.com/yunionio/docs/pull/106
