### ISSUE TITLE
baremetal、host、esxiagent 服务需要支持部署到多个 zone

### ISSUE THREAD

**Issue by zexi** [yunionio/onecloud#9068]
**What would you like to be added**:

现在的 onecloud-operator 会默认生成一个 zone0，然后所有的 baremetal, host, esxiagent 管理的节点都属于这个 zone，如果实际环境有多个机房，需要将这些服务和物理上的机房对应起来。

**建议方案**:

1. 给 k8s node 节点加上 onecloud.yunion.io/zone 的标签
2. operator 管理的 onecloudcluster list/watch k8s nodes 资源，根据 zone 标签创建对应的 daemonset, deployment，比如:

```bash
# 以下 k8s node 物理机房分别属于 wj, dx, jxq zone
k8s-node-wj-1 with label: onecloud.yunion.io/zone=wj
k8s-node-dx-1 with label: onecloud.yunion.io/zone=dx
k8s-node-jxq-1 with label: onecloud.yunion.io/zone=jxq

# 基于上面的 zone 标签，operator 就分别创建以下的 host daemonset, esxiagent&baremetal deployment
host daemonset:
  - default-host-wj
  - default-host-dx
  - default-host-jxq
esxiagent/baremetal deployment:
  - default-esxiagent/baremetal-wj
  - default-esxiagent/baremetal-dx
  - default-esxiagent/baremetal-jxq
```

/cc @swordqiu @yousong @wanyaoqi

**Comment by zexi** [comment]
https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#topologykubernetesioregion
或者说是否要支持 region + zone 级别的服务部署？根据 k8s node 的标签定义，可以给 node 加上:
topology.kubernetes.io/region
topology.kubernetes.io/zone

然后 operator 更具 region + zone 的标签，自动 group 出要部署的服务？

**Comment by wanyaoqi** [comment]
```
usage:
$ kubectl edit oc -n onecloud
 
zone: zone0         # default zone0
customZones:      # add zone wj and yf
  - wj
  - yf
 
```
https://github.com/yunionio/onecloud-operator/pull/358
