### ISSUE TITLE
虚拟机调整配置，新加的磁盘没有请求调度器

### ISSUE THREAD

**Issue by zexi** [yunionio/onecloud#9197]
**What happened**:

调用 climc server-change-config --disk 新添加磁盘的时候，后端的代码创建 disk 没有走调度，直接在 region 这边创建了，需要修改成走调度，拿到结果，再 attach disk 到 server 。

/cc @wanyaoqi

**Comment by wanyaoqi** [comment]
fixed https://github.com/yunionio/onecloud/pull/9398
