### ISSUE TITLE
虚拟机网卡界面只有添加没有删除

### ISSUE THREAD

**Issue by WangAnge** [yunionio/onecloud#9905]
**What happened**:
![image](https://user-images.githubusercontent.com/3390170/104717728-b3cf8580-5764-11eb-8916-4b6f902a1bba.png)
虚拟机网卡界面只有添加没有删除
**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by ioito** [comment]
> /cc @ioito 这个功能是计划在 3.7 做吗？

是在3.7，后端支持，可以先用 climc server-detach-network 解绑网卡
前端近期会开放这个按钮

**Comment by ioito** [comment]
![image](https://user-images.githubusercontent.com/13750250/110325837-cd999480-8052-11eb-9f4b-4e18542300ac.png)

最新版本的3.6前端已经支持卸载网卡
